dist: jammy
language: python
python:
  - "3.8"  # Use the development version of Python 3.8

env:
  - DJANGO_SETTINGS_MODULE="nyu_event.settings"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - black --check .
  - flake8 .
  - python manage.py migrate
  - python manage.py test
  - coverage run manage.py test  # Run tests with coverage
  - coverage report  # Generate coverage report
after_success:
  - coveralls


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "postgres"
  env: "postgres-dev"
  bucket_name: "elasticbeanstalk-us-east-1-891377257918"
  on:
    branch: main  # Deploy only from the main branch