dist: jammy
language: python
python:
  - "3.8" 

env:
  - DJANGO_SETTINGS_MODULE="nyu_event.settings"

install:
  - pip install --upgrade setuptools
  - pip install -r installed_dependencies.txt --extra-index-url https://download.pytorch.org/whl/cpu

services:
  - postgresql

before_script:
  - psql -c 'create database nyu_event;' -U postgres
  - psql -c "CREATE USER nyu_event WITH PASSWORD 'complexpassword123';" -U postgres
  - psql -c "ALTER ROLE nyu_event SET client_encoding TO 'utf8';" -U postgres
  - psql -c "ALTER ROLE nyu_event SET default_transaction_isolation TO 'read committed';" -U postgres
  - psql -c "ALTER ROLE nyu_event SET timezone TO 'UTC';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE nyu_event TO nyu_event;" -U postgres
  - psql -c 'DROP DATABASE IF EXISTS "test_nyu_event";' -U postgres

script:
  - black --check .
  - flake8 .
  - python manage.py migrate
  - python manage.py test
  - coverage run manage.py test
  - coverage report

after_success:
  - coveralls

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "us-east-1"
    app: "postgres"
    env: "dev-env"
    bucket_name: "elasticbeanstalk-us-east-1-891377257918"
    skip_cleanup: true
    on:
      branch: reviewhistory

  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "us-east-1"
    app: "postgres"
    env: "main"
    bucket_name: "elasticbeanstalk-us-east-1-891377257918"
    on:
      branch: master