branch-defaults:
  test-suspend:
    environment: postgres-dev2
environment-defaults:
  Postgres-env1:
    branch: null
    repository: null
global:
  application_name: postgres
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
