# Generated by Django 4.2.9 on 2024-03-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_banneduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="banneduser",
            name="unban_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
