# Generated by Django 4.2.9 on 2024-03-14 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0007_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspendedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("suspended_at", models.DateTimeField(auto_now_add=True)),
                ("unsuspended_at", models.DateTimeField(blank=True, null=True)),
                ("is_suspended", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
