branch-defaults:
  default:
    environment: null
    group_suffix: null
  deploy:
    environment: nyu-event2-dev
environment-defaults:
  nyu-event2-dev:
    branch: null
    repository: null
global:
  application_name: nyu_event2
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
